# Generated by Django 4.1.7 on 2023-03-15 22:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_photo_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 3, 15, 22, 54, 57, 609293, tzinfo=datetime.timezone.utc)),
        ),
    ]
