# Generated by Django 4.1.7 on 2023-03-17 20:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_photo_date_alter_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 17, 20, 24, 1, 807536, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 17, 20, 24, 1, 807536, tzinfo=datetime.timezone.utc)),
        ),
    ]
