# Generated by Django 4.1.7 on 2023-03-15 23:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_photo_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 3, 15, 23, 9, 52, 751490, tzinfo=datetime.timezone.utc)),
        ),
    ]
