# Generated by Django 4.1.7 on 2023-03-17 20:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_photo_date_alter_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 17, 16, 27, 22, 939614)),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 17, 16, 27, 22, 939614)),
        ),
    ]
