# Generated by Django 4.1.7 on 2023-03-18 14:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_photo_date_alter_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 18, 14, 51, 39, 550476)),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 18, 14, 51, 39, 550631)),
        ),
    ]
