# Generated by Django 4.1.7 on 2023-03-18 15:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_photo_date_alter_post_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField()),
                ('post_id', models.BigIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='photo',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 18, 11, 17, 31, 738390)),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 18, 11, 17, 31, 739390)),
        ),
    ]
