# Generated by Django 4.1.7 on 2023-03-19 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_photo_date_alter_post_date'),
        ('main_app', '0008_photo_user_alter_photo_date_alter_post_date'),
    ]

    operations = [
    ]
