# Generated by Django 4.1.7 on 2023-03-22 02:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_merge_20230319_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 21, 22, 16, 46, 321979)),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 21, 22, 16, 46, 321979)),
        ),
    ]
